### PR TITLE
Add a demo playground with shaders editor

### PR DESCRIPTION
**Pull request by risq**
As I was playing with the examples I thought it would be great to have some controls on the shaders for the playground page. Maybe you already made this, but I could only find individual examples. So I made a new (simle) demo page based on your playground, adding datGUI.js to allow live shaders edit. It automatically inspect shaders & uniforms and add GUI control for each one, so you can add any new shaders and it will bind their params to the GUI.

I don't know if you need this so I leave it here as a pull request, if this may help you.

Thanks for this awesome work - that's a great project !

*screenshot :*
untitled-1

### CODE REVIEW

**Comment by spite** [comment]
This is very good! Awesome, really!

I wanted to do something like this, you're right, but it would have been more like a layer editor. This fits the bill perfectly!

I'll be merging the PR, but first I have to make sure it still works with the latest changes to some of the passes. 

Thank you so much!

**Comment by risq** [comment]
No problem. I'd just like to add a way to allow pass stack order editing. Curently you can enable or disable any shader but can't modify its position in the composer stack. I'll try to find a way when I'll have a little time !

**Comment by spite** [comment]
Exactly. That's why I wanted to do it in a layer editor, a bit like Photoshop. @is-real wants to do a node-based graph editor. I think the order of the layer calls can be abstracted in another container or execution stack. I like the modular (as in it can be freely called) model of Wagner.

**Comment by risq** [comment]
I just updated the branch (https://github.com/risq/Wagner/commit/24963fd0faf4fc53d922ac6711180082b8923dae) with a stack manager UI which allows to move up and down the passes "layers" in the playground. I added a Stack class which handles the multi-pass process. It is, for now, extremely simple - and non-optimized - as it is just an experiment :) I'd just like to know what you thought about this kind of structure.

**Pull request closed without merging**
